on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    - release/*
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 01 00 * * *

 #ZAP Advanced
  zap_scan:
      runs-on: ubuntu-latest
      name: Scan the webapplication
      steps:
        - name: Checkout
          uses: 
            actions/checkout@v4          
          with:
            ref: master
            #run: docker network create zapnet 
            #network: '--net zapnet'
        - name: Create Docker network
          run: docker network create zapnet
          
        - name: Pull ZAP Docker Image
          run: docker pull ghcr.io/zaproxy/zaproxy:stable
        - name: ZAP Scan
          uses: zaproxy/action-full-scan@v0.12.0
          #uses: zap-full-scan.py -t <http://0.0.0.0:8080> [-a, -d]
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
            target: 'http://host.docker.internal:8080'
            #rules_file_name: '.zap/rules.tsv'
            cmd_options:  '-a'
