name: Semgrep CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  #schedule:
  #  - cron: '38 5 * * 3'
  
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v4
    - run: semgrep ci

  Checkout:
    needs: semgrep 
    name: Checkout
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
