name: Checkov Linter and Terraform Formatter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov
        run: checkov -d .

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.11.0"  

      - name: Format Terraform code
        run: terraform fmt -recursive

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automatically formatted Terraform code" || echo "No changes to commit"
          git push
